app: cas-mdcp-rplctr
service: ${self:app}-mssg
useDotenv: true

plugins:
  - '@nearst/serverless-dynalite'
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  environment:
    APP_NAME: ${self:app}-${sls:stage}
    SERVICE_NAME: ${self:service}-${sls:stage}
    EVENT_BUS_NAME: ${self:custom.resource.EventBusName}
    DYNAMODB_TABLE: ${self:service}-${sls:stage}-table
  apiGateway:
    restApiId: ${self:custom.resource.ApiGatewayRestApiId}
    restApiRootResourceId: ${self:custom.resource.ApiGatewayRestApiRootResourceId}
  tracing:
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - events:PutEvents
          Resource: '*'

custom:
  resource:
    ApiGatewayRestApiId:
      'Fn::ImportValue': ${self:app}-rsrc-${sls:stage}-ApiGatewayRestApiId
    ApiGatewayRestApiRootResourceId:
      'Fn::ImportValue': ${self:app}-rsrc-${sls:stage}-ApiGatewayRestApiRootResourceId
    EventBusName:
      'Fn::ImportValue': ${self:app}-rsrc-${sls:stage}-EventBusName
  serverless-offline:
    reloadHandler: true

functions:
  httpMessagePost:
    handler: ./src/handler.handler
    events:
      - http:
          path: /message
          method: post
          cors: true

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: _pk
            AttributeType: S
          - AttributeName: _sk
            AttributeType: S
          - AttributeName: _gsi1pk
            AttributeType: S
          - AttributeName: _gsi1sk
            AttributeType: S
        KeySchema:
          - AttributeName: _pk
            KeyType: HASH
          - AttributeName: _sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gsi1
            KeySchema:
              - AttributeName: _gsi1pk
                KeyType: HASH
              - AttributeName: _gsi1sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
