service: telemedicine-schedule-resource
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    apiGateway: true
    lambda: true

functions:
  httpRoot:
    handler: ./src/http-root.handler
    events:
      - http:
          path: /
          method: get

resources:
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:service}-${sls:stage}-ApiGatewayRestApiId

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ${self:service}-${sls:stage}-ApiGatewayRestApiRootResourceId
